### ISSUE TITLE
Spaces in entity name

### ISSUE THREAD

**Issue by awinogradov** [bem-sdk/bem-walk#102]
This one `/Button Action/Button Action.svg` doesn't work :(
But this `/ButtonAction/ButtonAction.svg` is ok.

Bug or feature?

**Comment by blond** [comment]
feature :wink:

See `wordPattern` in your naming convention. By default `[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*`.

https://github.com/bem-sdk/bem-naming/blob/master/test/presets/original/parse.test.js#L8
