### ISSUE TITLE
Support wildcards

### ISSUE THREAD

**Issue by blond** [bem-sdk/bem-walk#16]
Need use [`glob`](https://github.com/isaacs/node-glob).

Now we need to specify all levels:

```js
var walk = require('bem-walk');

walk([
    'libs/bem-core/common.blocks',
    'libs/bem-core/desktop.blocks',
    'libs/bem-components/common.blocks',
    'libs/bem-components/desktop.blocks',
    'libs/bem-components/design/common.blocks',
    'libs/bem-components/design/desktop.blocks',
    'common.blocks', 
    'desktop.blocks'
]);
```

If use wildcards:

```js
var walk = require('bem-walk');

walk([
    'libs/**/+(common|desktop).blocks'
    '*.blocks'
]);
```

**Comment by zxqfox** [comment]
Glob reading dirs by self. Is it fast enough? Is it furious?

**Comment by zxqfox** [comment]
Are you sure about glob? Can we just use `minimatch`?

**Comment by andrewblond** [comment]
`minimatch` work with strings, `glob` with file system. We need to know what the levels are on the file system, so our choice is a tool `glob`.

> Glob reading dirs by self. Is it fast enough? Is it furious?

Need to check, but it seems that the speed should not be reduced for cases that do not use wildcards.

**Comment by zxqfox** [comment]
Anyway using glob here looks like overkill.

**Comment by zxqfox** [comment]
:-1: Since `bem-walk` need this only for initial levels lookup I'd prefer to not include `glob` as dependency. It's really easy to make `bem-walk-glob` package with these functionality so there are no vital reasons to use it here.

**Comment by blond** [comment]
@zxqfox you want `fs.readdir` + `minimatch`?

**Comment by zxqfox** [comment]
Why we need it at all here?
