### ISSUE TITLE
Что-то знать про НЕ БЭМ сущности

### ISSUE THREAD

**Issue by eGavr** [bem-sdk/bem-walk#31]
Пожалуй стоит давать какую-то инфу про файл, который не принадледжит никакой БЭМ сущности, а не просто пропускать его; например, имени и полного пути было бы достаточно, ну и какое-то отдельное поле , которое бы говорило, что это не БЭМ сущность.

В общем считаю, что это должен быть обычный вывод, не ошибка, не варнинг и т д.

**Comment by zxqfox** [comment]
Хочешь и тут про BEAVIS что-то захардкодить? ;-)

**Comment by blond** [comment]
@zxqfox `BEAVIS` -> `BEViS` ;)

Тут скорее речь о файлах, у которых именование либо не по БЭМ, либо по БЭМ, но не подходит по схеме: `blocks/block/bock.js` (актуально для `nested`). 

Нужно для линтерства и прочих догадок.

**Comment by blond** [comment]
Закрываю в пользу #52
