### ISSUE TITLE
Add any docs to README

### ISSUE THREAD

**Issue by veged** [bem-sdk/bem-walk#32]
Please ;-)

**Comment by zxqfox** [comment]
@veged It's in very early state ;-( Sure we'll do!

**Comment by tadatuta** [comment]
even though it's an early state, it works just well, so for an example you may refer to https://github.com/bem/bem-walk/blob/master/test/lib/assert.js

**Comment by zxqfox** [comment]
@tadatuta U know, PR r willkommen!

**Comment by blond** [comment]
fixed
